/*

    Warsaw Wrapper for Warsaw Agent
    GAS Tecnologia - 2015
*/
/* Version 1.4.3.15 */
'use strict';window.WarsawWrapper=function(){function d(a,c){this.e=a;this.b=c}d.prototype.IsInstalled=function(a,c,b){"function"!==typeof a&&(a=function(){});"function"!==typeof c&&(c=function(){});"function"!==typeof b&&(b=function(){});b={onsuccess:function(b){'"1"'===b||"1"===b||1===b?a():c()},onerror:b,d:this.getIsInstalledCommand(),params:{s:this.b}};warsawExec(b)};d.prototype.Update=function(a){"function"!==typeof a&&(a=function(){});var c={onerror:function(b){"Close"!=b&&a(b)},d:this.getUpdateCommand(),
params:{s:this.b}};warsawExec(c)};d.prototype.Install=function(a,c,b){"undefined"===typeof b&&(b=30);"function"!==typeof c&&(c=function(){});"function"!==typeof a&&(a=function(){});var e={d:this.getInstallCommand(),params:{s:this.b}};warsawExec(e);this.Verifier(c,a,b)};d.prototype.F10=function(a,c,b,e,d,f,h,g){"function"!==typeof h&&(h=function(){});"function"!==typeof g&&(g=function(){});warsawExec({onsuccess:h,d:f,onerror:g,params:{a:a,c:c,u:b,p:e,s:d,r:this.e}})};d.prototype.F13=function(a,c,b,
e){"function"!==typeof b&&(b=function(){});"function"!==typeof e&&(e=function(){});a={onsuccess:b,d:c,onerror:e,params:{d:JSON.stringify(a),c:this.e}};warsawExec(a)};d.prototype.getUpdateCommand=function(){var a={d:JSON.stringify({n:"Update"})};return JSON.stringify(a)};d.prototype.getInstallCommand=function(){var a={d:JSON.stringify({n:"Install"})};return JSON.stringify(a)};d.prototype.getIsInstalledCommand=function(){var a={d:JSON.stringify({n:"IsInstalled",rs:0})};return JSON.stringify(a)};d.prototype.Encrypt=
function(a,c,b,e,d,f){"function"!==typeof d&&(d=function(){});"function"!==typeof f&&(f=function(){});a={onsuccess:d,onerror:f,d:a,params:{s:JSON.stringify({salt:e?"1":"0",data:c,user_key:b})}};warsawExec(a)};d.prototype.Info=function(a,c,b){"function"!==typeof c&&(c=function(){});"function"!==typeof b&&(b=function(){});warsawExec({onsuccess:c,d:a,onerror:b})};d.prototype.Digest=function(a,c,b){"function"!==typeof c&&(c=function(){});"function"!==typeof b&&(b=function(){});warsawExec({onsuccess:c,
d:a,onerror:b})};d.prototype.Verifier=function(a,c,b){var d=setInterval(function(a,b,c){return function(){var g={onsuccess:function(a){if('"1"'===a||"1"===a||1===a)clearInterval(d),d=0,c()},onerror:function(a){0!==d&&(clearInterval(d),d=0,b(a))},d:a.getIsInstalledCommand(),params:{s:a.b}};warsawExec(g)}}(this,a,c),3E3);setTimeout(function(){0!==d&&(clearInterval(d),d=0,a("Not installed"))},1E3*b)};return d}();
